### ISSUE TITLE
Implement from UML three classes with test cases

### ISSUE THREAD

**Issue by dadi-vardhan** [dadi-vardhan/SDP#25]
**Classes to be implemented:**

1. Uncertain <T> 
2. Random Primitive
3. Gaussian

**Tests:**
1. Naive life
2. Sensor life

**Comment by deebuls** [comment]
Priority:

Code class implementation without the logic.

All the test cases (possibly with the logic)

**Comment by deebuls** [comment]
@krishnakool @HammamWahab  updates?
